export const stockSectorList = [
    {
        particulars: "HDFC Bank",
        symbol: "HDFCBANK.NS",
        quantity: 30,
        purchasePrice: 1490,
        sector: "Financial",
        exchange: "NSE",
    },
    {
        particulars: "Bajaj Finance",
        symbol: "BAJFINANCE.NS",
        quantity: 20,
        purchasePrice: 4590,
        sector: "Financial",
        exchange: "NSE",
    },
    {
        particulars: "ICICI Bank",
        symbol: "ICICIBANK.NS",
        quantity: 20,
        purchasePrice: 4590,
        sector: "Financial",
        exchange: "NSE",
    },
    {
        particulars: "Bajaj Housing",
        symbol: "BAJAJHFL.NS",
        quantity: 47,
        purchasePrice: 2154,
        sector: "Financial",
        exchange: "NSE",
    },
    {
        particulars: "Savani Financials",
        symbol: "SAVFI.BO",
        quantity: 25,
        purchasePrice: 2454,
        sector: "Financial",
        exchange: "BSE",
    },
    {
        particulars: "Affle India",
        symbol: "AFFLE.NS",
        quantity: 36,
        purchasePrice: 8547,
        sector: "Technical",
        exchange: "NSE",
    },
    {
        particulars: "LTI Mindtree",
        symbol: "LTIM.NS",
        quantity: 78,
        purchasePrice: 8961,
        sector: "Technical",
        exchange: "NSE",
    },
    {
        particulars: "KPIT Tech",
        symbol: "KPITTECH.NS",
        quantity: 61,
        purchasePrice: 672,
        sector: "Technical",
        exchange: "NSE",
    },
    {
        particulars: "Tata Tech",
        symbol: "TATATECH.NS",
        quantity: 63,
        purchasePrice: 1072,
        sector: "Technical",
        exchange: "NSE",
    },
    {
        particulars: "BLS E-Services",
        symbol: "BLSE.NS",
        quantity: 191,
        purchasePrice: 232,
        sector: "Technical",
        exchange: "NSE",
    },
    {
        particulars: "Tanla",
        symbol: "TANLA.NS",
        quantity: 45,
        purchasePrice: 1134,
        sector: "Technical",
        exchange: "NSE",
    },
    {
        particulars: "Dmart",
        symbol: "DMART.NS",
        quantity: 27,
        purchasePrice: 3777,
        sector: "Consumer",
        exchange: "NSE",
    },
    {
        particulars: "Tata Consumer",
        symbol: "TATACONSUM.NS",
        quantity: 90,
        purchasePrice: 845,
        sector: "Consumer",
        exchange: "NSE",
    },
    {
        particulars: "Pidilite",
        symbol: "PIDILITIND.NS",
        quantity: 36,
        purchasePrice: 2376,
        sector: "Consumer",
        exchange: "NSE",
    },
    {
        particulars: "Tata Power",
        symbol: "TATAPOWER.NS",
        quantity: 225,
        purchasePrice: 224,
        sector: "Power",
        exchange: "NSE",
    },
    {
        particulars: "KPI Green",
        symbol: "KPIGREEN.NS",
        quantity: 50,
        purchasePrice: 875,
        sector: "Power",
        exchange: "NSE",
    },
    {
        particulars: "Suzlon",
        symbol: "SUZLON.NS",
        quantity: 450,
        purchasePrice: 44,
        sector: "Power",
        exchange: "NSE",
    },
    {
        particulars: "Gensol",
        symbol: "GENSOL.BO",
        quantity: 45,
        purchasePrice: 998,
        sector: "Power",
        exchange: "BSE",
    },
    {
        particulars: "Hariom Pipes",
        symbol: "HARIOMPIPE.NS",
        quantity: 60,
        purchasePrice: 580,
        sector: "Pipe Sector",
        exchange: "NSE",
    },
    {
        particulars: "Astral",
        symbol: "ASTRAL.NS",
        quantity: 56,
        purchasePrice: 1517,
        sector: "Pipe Sector",
        exchange: "NSE",
    },
    {
        particulars: "Polycab",
        symbol: "POLYCAB.NS",
        quantity: 28,
        purchasePrice: 2818,
        sector: "Pipe Sector",
        exchange: "NSE",
    },
    {
        particulars: "Clean Science",
        symbol: "CLEAN.NS",
        quantity: 32,
        purchasePrice: 1610,
        sector: "Others",
        exchange: "NSE",
    },
    {
        particulars: "Deepak Nitrite",
        symbol: "DEEPAKNTR.NS",
        quantity: 27,
        purchasePrice: 2248,
        sector: "Others",
        exchange: "NSE",
    },
    {
        particulars: "Fine Organic",
        symbol: "FINEORG.NS",
        quantity: 16,
        purchasePrice: 4284,
        sector: "Others",
        exchange: "NSE",
    },
    {
        particulars: "Gravita",
        symbol: "GRAVITA.NS",
        quantity: 8,
        purchasePrice: 2037,
        sector: "Others",
        exchange: "NSE",
    },
    {
        particulars: "SBI Life",
        symbol: "SBILIFE.NS",
        quantity: 49,
        purchasePrice: 1197,
        sector: "Others",
        exchange: "NSE",
    },
];